/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'targetDaysPerWeek' : IDL.Nat,
});
export const MotivationTone = IDL.Variant({
  'calm' : IDL.Null,
  'energetic' : IDL.Null,
  'professional' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'motivationTone' : MotivationTone,
  'name' : IDL.Text,
  'sleepTime' : IDL.Nat,
  'wakeTime' : IDL.Nat,
  'goals' : IDL.Vec(IDL.Text),
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'priority' : TaskPriority,
  'estimatedMinutes' : IDL.Nat,
});
export const TimeBlock = IDL.Record({
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'notes' : IDL.Text,
});
export const HabitWithStats = IDL.Record({
  'streak' : IDL.Nat,
  'habit' : Habit,
  'completionRate' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createHabit' : IDL.Func([Habit], [IDL.Nat], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'createTask' : IDL.Func([Task], [IDL.Nat], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'generateSchedule' : IDL.Func([IDL.Text], [IDL.Vec(TimeBlock)], []),
  'getAllHabits' : IDL.Func([], [IDL.Vec(HabitWithStats)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGenerationCountForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getHabitWeeklySummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'habit' : Habit,
            'completionRate' : IDL.Nat,
            'checkIns' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getMotivationalMessage' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSchedule' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(TimeBlock))],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeMotivationalMessage' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  'updateHabit' : IDL.Func([IDL.Nat, Habit], [], []),
  'updateSchedule' : IDL.Func([IDL.Text, IDL.Vec(TimeBlock)], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'targetDaysPerWeek' : IDL.Nat,
  });
  const MotivationTone = IDL.Variant({
    'calm' : IDL.Null,
    'energetic' : IDL.Null,
    'professional' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'isPremium' : IDL.Bool,
    'motivationTone' : MotivationTone,
    'name' : IDL.Text,
    'sleepTime' : IDL.Nat,
    'wakeTime' : IDL.Nat,
    'goals' : IDL.Vec(IDL.Text),
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'priority' : TaskPriority,
    'estimatedMinutes' : IDL.Nat,
  });
  const TimeBlock = IDL.Record({
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const HabitWithStats = IDL.Record({
    'streak' : IDL.Nat,
    'habit' : Habit,
    'completionRate' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createHabit' : IDL.Func([Habit], [IDL.Nat], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'createTask' : IDL.Func([Task], [IDL.Nat], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'generateSchedule' : IDL.Func([IDL.Text], [IDL.Vec(TimeBlock)], []),
    'getAllHabits' : IDL.Func([], [IDL.Vec(HabitWithStats)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGenerationCountForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getHabitWeeklySummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'habit' : Habit,
              'completionRate' : IDL.Nat,
              'checkIns' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getMotivationalMessage' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSchedule' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(TimeBlock))],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeMotivationalMessage' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'updateHabit' : IDL.Func([IDL.Nat, Habit], [], []),
    'updateSchedule' : IDL.Func([IDL.Text, IDL.Vec(TimeBlock)], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };