/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'targetDaysPerWeek' : bigint,
}
export interface HabitWithStats {
  'streak' : bigint,
  'habit' : Habit,
  'completionRate' : bigint,
}
export type MotivationTone = { 'calm' : null } |
  { 'energetic' : null } |
  { 'professional' : null };
export interface Task {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'date' : string,
  'description' : string,
  'priority' : TaskPriority,
  'estimatedMinutes' : bigint,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TimeBlock {
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'notes' : string,
}
export interface UserProfile {
  'isPremium' : boolean,
  'motivationTone' : MotivationTone,
  'name' : string,
  'sleepTime' : bigint,
  'wakeTime' : bigint,
  'goals' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInHabit' : ActorMethod<[bigint, string], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createHabit' : ActorMethod<[Habit], bigint>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createTask' : ActorMethod<[Task], bigint>,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'generateSchedule' : ActorMethod<[string], Array<TimeBlock>>,
  'getAllHabits' : ActorMethod<[], Array<HabitWithStats>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGenerationCountForDate' : ActorMethod<[string], bigint>,
  'getHabitWeeklySummary' : ActorMethod<
    [bigint],
    [] | [
      { 'habit' : Habit, 'completionRate' : bigint, 'checkIns' : Array<string> }
    ]
  >,
  'getMotivationalMessage' : ActorMethod<[string, boolean], [] | [string]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSchedule' : ActorMethod<[string], [] | [Array<TimeBlock>]>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasksByDate' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeMotivationalMessage' : ActorMethod<[string, boolean], string>,
  'updateHabit' : ActorMethod<[bigint, Habit], undefined>,
  'updateSchedule' : ActorMethod<[string, Array<TimeBlock>], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];