/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type GenerateScheduleResult = {
    __kind__: "ok";
    ok: Array<TimeBlock>;
} | {
    __kind__: "limitReached";
    limitReached: null;
} | {
    __kind__: "profileNotFound";
    profileNotFound: null;
};
export interface HabitWithStats {
    streak: bigint;
    habit: Habit;
    completionRate: bigint;
}
export interface Task {
    id: bigint;
    title: string;
    isCompleted: boolean;
    date: string;
    description: string;
    priority: TaskPriority;
    estimatedMinutes: bigint;
}
export interface TimeBlock {
    startTime: bigint;
    title: string;
    endTime: bigint;
    notes: string;
}
export interface Habit {
    id: bigint;
    name: string;
    description: string;
    targetDaysPerWeek: bigint;
}
export interface UserProfile {
    motivationTone: MotivationTone;
    name: string;
    sleepTime: bigint;
    wakeTime: bigint;
    subscriptionStatus: SubscriptionStatus;
    goals: Array<string>;
}
export enum MotivationTone {
    calm = "calm",
    energetic = "energetic",
    professional = "professional"
}
export enum SubscriptionStatus {
    premium = "premium",
    free = "free",
    lifetime = "lifetime"
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkInHabit(habitId: bigint, date: string): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    createHabit(habit: Habit): Promise<bigint>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    createTask(task: Task): Promise<bigint>;
    deleteHabit(habitId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    generateSchedule(date: string): Promise<GenerateScheduleResult>;
    getAllHabits(): Promise<Array<HabitWithStats>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGenerationCountForDate(date: string): Promise<bigint>;
    getHabitWeeklySummary(habitId: bigint): Promise<{
        habit: Habit;
        completionRate: bigint;
        checkIns: Array<string>;
    } | null>;
    getIsPremium(): Promise<boolean>;
    getMotivationalMessage(date: string, isEvening: boolean): Promise<string | null>;
    getProfile(): Promise<UserProfile | null>;
    getSchedule(date: string): Promise<Array<TimeBlock> | null>;
    getSubscriptionStatus(): Promise<SubscriptionStatus | null>;
    getTask(taskId: bigint): Promise<Task | null>;
    getTasksByDate(date: string): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeMotivationalMessage(date: string, isEvening: boolean): Promise<string>;
    updateHabit(habitId: bigint, habit: Habit): Promise<void>;
    updateSchedule(date: string, blocks: Array<TimeBlock>): Promise<void>;
    updateTask(taskId: bigint, task: Task): Promise<void>;
    upgradeSubscription(status: SubscriptionStatus): Promise<void>;
}
import type { GenerateScheduleResult as _GenerateScheduleResult, Habit as _Habit, MotivationTone as _MotivationTone, SubscriptionStatus as _SubscriptionStatus, Task as _Task, TaskPriority as _TaskPriority, TimeBlock as _TimeBlock, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkInHabit(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInHabit(arg0, arg1);
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async createHabit(arg0: Habit): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteHabit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async generateSchedule(arg0: string): Promise<GenerateScheduleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSchedule(arg0);
                return from_candid_GenerateScheduleResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSchedule(arg0);
            return from_candid_GenerateScheduleResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHabits(): Promise<Array<HabitWithStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHabits();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGenerationCountForDate(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenerationCountForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenerationCountForDate(arg0);
            return result;
        }
    }
    async getHabitWeeklySummary(arg0: bigint): Promise<{
        habit: Habit;
        completionRate: bigint;
        checkIns: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitWeeklySummary(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitWeeklySummary(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIsPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsPremium();
            return result;
        }
    }
    async getMotivationalMessage(arg0: string, arg1: boolean): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalMessage(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalMessage(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchedule(arg0: string): Promise<Array<TimeBlock> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedule(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedule(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionStatus(): Promise<SubscriptionStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionStatus();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionStatus();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByDate(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByDate(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByDate(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async storeMotivationalMessage(arg0: string, arg1: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMotivationalMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMotivationalMessage(arg0, arg1);
            return result;
        }
    }
    async updateHabit(arg0: bigint, arg1: Habit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, arg1);
            return result;
        }
    }
    async updateSchedule(arg0: string, arg1: Array<TimeBlock>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSchedule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSchedule(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeSubscription(arg0: SubscriptionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeSubscription(to_candid_SubscriptionStatus_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeSubscription(to_candid_SubscriptionStatus_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_GenerateScheduleResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenerateScheduleResult): GenerateScheduleResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MotivationTone_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MotivationTone): MotivationTone {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        habit: _Habit;
        completionRate: bigint;
        checkIns: Array<string>;
    }]): {
    habit: Habit;
    completionRate: bigint;
    checkIns: Array<string>;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_TimeBlock>]): Array<TimeBlock> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionStatus]): SubscriptionStatus | null {
    return value.length === 0 ? null : from_candid_SubscriptionStatus_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isCompleted: boolean;
    date: string;
    description: string;
    priority: _TaskPriority;
    estimatedMinutes: bigint;
}): {
    id: bigint;
    title: string;
    isCompleted: boolean;
    date: string;
    description: string;
    priority: TaskPriority;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        isCompleted: value.isCompleted,
        date: value.date,
        description: value.description,
        priority: from_candid_TaskPriority_n18(_uploadFile, _downloadFile, value.priority),
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motivationTone: _MotivationTone;
    name: string;
    sleepTime: bigint;
    wakeTime: bigint;
    subscriptionStatus: _SubscriptionStatus;
    goals: Array<string>;
}): {
    motivationTone: MotivationTone;
    name: string;
    sleepTime: bigint;
    wakeTime: bigint;
    subscriptionStatus: SubscriptionStatus;
    goals: Array<string>;
} {
    return {
        motivationTone: from_candid_MotivationTone_n23(_uploadFile, _downloadFile, value.motivationTone),
        name: value.name,
        sleepTime: value.sleepTime,
        wakeTime: value.wakeTime,
        subscriptionStatus: from_candid_SubscriptionStatus_n25(_uploadFile, _downloadFile, value.subscriptionStatus),
        goals: value.goals
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TimeBlock>;
} | {
    limitReached: null;
} | {
    profileNotFound: null;
}): {
    __kind__: "ok";
    ok: Array<TimeBlock>;
} | {
    __kind__: "limitReached";
    limitReached: null;
} | {
    __kind__: "profileNotFound";
    profileNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "limitReached" in value ? {
        __kind__: "limitReached",
        limitReached: value.limitReached
    } : "profileNotFound" in value ? {
        __kind__: "profileNotFound",
        profileNotFound: value.profileNotFound
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    calm: null;
} | {
    energetic: null;
} | {
    professional: null;
}): MotivationTone {
    return "calm" in value ? MotivationTone.calm : "energetic" in value ? MotivationTone.energetic : "professional" in value ? MotivationTone.professional : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
} | {
    lifetime: null;
}): SubscriptionStatus {
    return "premium" in value ? SubscriptionStatus.premium : "free" in value ? SubscriptionStatus.free : "lifetime" in value ? SubscriptionStatus.lifetime : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n16(_uploadFile, _downloadFile, x));
}
function to_candid_MotivationTone_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationTone): _MotivationTone {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isCompleted: boolean;
    date: string;
    description: string;
    priority: TaskPriority;
    estimatedMinutes: bigint;
}): {
    id: bigint;
    title: string;
    isCompleted: boolean;
    date: string;
    description: string;
    priority: _TaskPriority;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        isCompleted: value.isCompleted,
        date: value.date,
        description: value.description,
        priority: to_candid_TaskPriority_n11(_uploadFile, _downloadFile, value.priority),
        estimatedMinutes: value.estimatedMinutes
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motivationTone: MotivationTone;
    name: string;
    sleepTime: bigint;
    wakeTime: bigint;
    subscriptionStatus: SubscriptionStatus;
    goals: Array<string>;
}): {
    motivationTone: _MotivationTone;
    name: string;
    sleepTime: bigint;
    wakeTime: bigint;
    subscriptionStatus: _SubscriptionStatus;
    goals: Array<string>;
} {
    return {
        motivationTone: to_candid_MotivationTone_n5(_uploadFile, _downloadFile, value.motivationTone),
        name: value.name,
        sleepTime: value.sleepTime,
        wakeTime: value.wakeTime,
        subscriptionStatus: to_candid_SubscriptionStatus_n7(_uploadFile, _downloadFile, value.subscriptionStatus),
        goals: value.goals
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MotivationTone): {
    calm: null;
} | {
    energetic: null;
} | {
    professional: null;
} {
    return value == MotivationTone.calm ? {
        calm: null
    } : value == MotivationTone.energetic ? {
        energetic: null
    } : value == MotivationTone.professional ? {
        professional: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    premium: null;
} | {
    free: null;
} | {
    lifetime: null;
} {
    return value == SubscriptionStatus.premium ? {
        premium: null
    } : value == SubscriptionStatus.free ? {
        free: null
    } : value == SubscriptionStatus.lifetime ? {
        lifetime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
